# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rgbio_wrappers", use_symbols = TRUE, package_name = "rgbio")

#' @usage NULL
#' @useDynLib rgbio, .registration = TRUE
NULL

read_genbank_rs <- function(path) .Call(wrap__read_genbank_rs, path)

write_genbank_rs <- function(path, sequence, features, metadata) .Call(wrap__write_genbank_rs, path, sequence, features, metadata)


# nolint end
